name: 'Deploy'

on: push

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.24.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build:site

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./apps/site
